"use client";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";

const metadata = {
  title: "Voices of Bokamuso",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap"
          rel="stylesheet"
        />
        {/* preload the images */}
        <link rel="preload" href="/hero.jpg" as="image" />
        <link rel="preload" href="/hero-bg1.jpg" as="image" />
        <link rel="preload" href="/hero-bg2.jpg" as="image" />
        <link rel="preload" href="/hero-bg3.jpg" as="image" />
      
      </head>
      <body className={`font-sans`}>
        <main>
          <HeroUIProvider>
            {children}
          </HeroUIProvider>
        </main>
      </body>
    </html>
  );
}
